spring.application.name=media-server
server.address=0.0.0.0
server.port=8080
media.movies.path=C:/media-library/movies
media.shows.path=C:/media-library/shows
spring.datasource.url=jdbc:sqlite:./data/media-server.db?foreign_keys=on&busy_timeout=5000
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-sqlite.sql
spring.jpa.defer-datasource-initialization=false

spring.datasource.hikari.maximum-pool-size=1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false